---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags:
        - apt_get
      when: ansible_os_family=="Debian"

    - name: Install httpd
      package:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat" 

    - name: Start httpd daemon
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat" 

    - name: Create user kobby
      user:
        name: Kobby
        comment: Kwabena Smith
        shell: /bin/bash

    - name: Create group
      group:
        name: Cloudteam
        state: present

    - name: Create Index File
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output
      tags:
        - file_create
        
    - name: Create directory
      file:
        path: /tmp/os
        state: directory
  
    - name: Copy content to index
      copy:
        dest: file_output.diff.before.path
        content: '<h1>This is created using ansible</h1>'
